// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krtbceqdcyzdnxbdzfyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtydGJjZXFkY3l6ZG54YmR6ZnlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNDM0NzQsImV4cCI6MjA3NDYxOTQ3NH0.Y5TG7H7lHiHqwH2sHn7OAHOkHAbnRQ2TQUUTx4zdF-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});